/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bootstrap */
        get: operations["get_bootstrap_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /** Start Job */
        post: operations["start_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Job */
        post: operations["stop_job_jobs__job_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Log Channels */
        get: operations["list_log_channels_logs_channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log Snapshot */
        get: operations["get_log_snapshot_logs__channel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{channel_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Log Channel */
        get: operations["stream_log_channel_logs__channel_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runtime Status */
        get: operations["get_runtime_status_runtime_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime-control/{runtime_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Runtime */
        post: operations["start_runtime_runtime_control__runtime_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime-control/{runtime_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Runtime */
        post: operations["stop_runtime_runtime_control__runtime_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spot Snapshot */
        get: operations["get_spot_snapshot_spot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/futures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Futures Snapshot */
        get: operations["get_futures_snapshot_futures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Telegram Snapshot */
        get: operations["get_telegram_snapshot_telegram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/connectivity-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Telegram Connectivity Check */
        post: operations["run_telegram_connectivity_check_telegram_connectivity_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown */
        post: operations["shutdown_admin_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppSessionInfo */
        AppSessionInfo: {
            /** Session Id */
            session_id: string;
            /** Transport Base Url */
            transport_base_url: string;
            /** Events Url */
            events_url: string;
        };
        /** BootstrapPayload */
        BootstrapPayload: {
            /** App Name */
            app_name: string;
            /** Version */
            version: string;
            session: components["schemas"]["AppSessionInfo"];
            capabilities: components["schemas"]["UiCapabilities"];
            /** Routes */
            routes: string[];
        };
        /** DataBackfillJobPayload */
        DataBackfillJobPayload: {
            /**
             * Symbol
             * @default BTCUSDT
             * @constant
             */
            symbol: "BTCUSDT";
            /**
             * Category
             * @default spot
             * @constant
             */
            category: "spot";
            /**
             * Intervals
             * @default [
             *       "1m"
             *     ]
             */
            intervals: [
                "1m"
            ];
        };
        /** DataIntegrityJobPayload */
        DataIntegrityJobPayload: {
            /**
             * Symbol
             * @default BTCUSDT
             * @constant
             */
            symbol: "BTCUSDT";
            /**
             * Category
             * @default spot
             * @constant
             */
            category: "spot";
            /**
             * Intervals
             * @default [
             *       "1m"
             *     ]
             */
            intervals: [
                "1m"
            ];
        };
        /** EmptyJobPayload */
        EmptyJobPayload: Record<string, never>;
        /** FuturesFill */
        FuturesFill: {
            /** Account Type */
            account_type: string;
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /** Exec Id */
            exec_id: string;
            /** Order Id */
            order_id?: string | null;
            /** Order Link Id */
            order_link_id?: string | null;
            /**
             * Price
             * @default 0
             */
            price: number;
            /**
             * Qty
             * @default 0
             */
            qty: number;
            /** Exec Fee */
            exec_fee?: number | null;
            /** Fee Currency */
            fee_currency?: string | null;
            /** Is Maker */
            is_maker?: boolean | null;
            /** Exec Time Ms */
            exec_time_ms?: number | null;
            /** Created At Utc */
            created_at_utc?: string | null;
        };
        /** FuturesOpenOrder */
        FuturesOpenOrder: {
            /** Account Type */
            account_type: string;
            /** Symbol */
            symbol: string;
            /** Side */
            side?: string | null;
            /** Order Id */
            order_id?: string | null;
            /** Order Link Id */
            order_link_id?: string | null;
            /** Order Type */
            order_type?: string | null;
            /** Time In Force */
            time_in_force?: string | null;
            /** Price */
            price?: number | null;
            /** Qty */
            qty?: number | null;
            /** Status */
            status: string;
            /** Reduce Only */
            reduce_only?: boolean | null;
            /** Close On Trigger */
            close_on_trigger?: boolean | null;
            /** Strategy Owner */
            strategy_owner?: string | null;
            /** Updated At Utc */
            updated_at_utc?: string | null;
        };
        /** FuturesPosition */
        FuturesPosition: {
            /** Account Type */
            account_type: string;
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /** Position Idx */
            position_idx: number;
            /** Margin Mode */
            margin_mode?: string | null;
            /** Leverage */
            leverage?: number | null;
            /**
             * Qty
             * @default 0
             */
            qty: number;
            /** Entry Price */
            entry_price?: number | null;
            /** Mark Price */
            mark_price?: number | null;
            /** Liq Price */
            liq_price?: number | null;
            /** Unrealized Pnl */
            unrealized_pnl?: number | null;
            /** Take Profit */
            take_profit?: number | null;
            /** Stop Loss */
            stop_loss?: number | null;
            /** Protection Status */
            protection_status: string;
            /** Source Of Truth */
            source_of_truth: string;
            /**
             * Recovered From Exchange
             * @default false
             */
            recovered_from_exchange: boolean;
            /** Strategy Owner */
            strategy_owner?: string | null;
            /** Updated At Utc */
            updated_at_utc?: string | null;
        };
        /** FuturesReadSnapshot */
        FuturesReadSnapshot: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "fixture" | "compatibility";
            summary: components["schemas"]["FuturesReadSummary"];
            /** Positions */
            positions?: components["schemas"]["FuturesPosition"][];
            /** Active Orders */
            active_orders?: components["schemas"]["FuturesOpenOrder"][];
            /** Recent Fills */
            recent_fills?: components["schemas"]["FuturesFill"][];
            truncated?: components["schemas"]["FuturesReadTruncation"];
        };
        /** FuturesReadSummary */
        FuturesReadSummary: {
            /** Account Type */
            account_type: string;
            /**
             * Positions Count
             * @default 0
             */
            positions_count: number;
            /**
             * Protected Positions Count
             * @default 0
             */
            protected_positions_count: number;
            /**
             * Attention Positions Count
             * @default 0
             */
            attention_positions_count: number;
            /**
             * Recovered Positions Count
             * @default 0
             */
            recovered_positions_count: number;
            /**
             * Open Orders Count
             * @default 0
             */
            open_orders_count: number;
            /**
             * Recent Fills Count
             * @default 0
             */
            recent_fills_count: number;
            /**
             * Unrealized Pnl Total
             * @default 0
             */
            unrealized_pnl_total: number;
        };
        /** FuturesReadTruncation */
        FuturesReadTruncation: {
            /**
             * Positions
             * @default false
             */
            positions: boolean;
            /**
             * Active Orders
             * @default false
             */
            active_orders: boolean;
            /**
             * Recent Fills
             * @default false
             */
            recent_fills: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Session Id */
            session_id: string;
        };
        /** JobDetails */
        JobDetails: {
            /** Job Id */
            job_id: string;
            /** Job Type */
            job_type: string;
            state: components["schemas"]["JobState"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Started At */
            started_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Exit Code */
            exit_code?: number | null;
            /** Last Error */
            last_error?: string | null;
            /** Log Stream Id */
            log_stream_id?: string | null;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "starting" | "running" | "stopping" | "completed" | "failed" | "cancelled" | "orphaned";
        /** JobSummary */
        JobSummary: {
            /** Job Id */
            job_id: string;
            /** Job Type */
            job_type: string;
            state: components["schemas"]["JobState"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** LogChannel */
        LogChannel: {
            /**
             * Channel Id
             * @enum {string}
             */
            channel_id: "app" | "jobs" | "desktop" | "legacy-runtime";
            /** Label */
            label: string;
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "memory" | "events" | "file" | "compatibility";
            /**
             * Available
             * @default false
             */
            available: boolean;
        };
        /** LogChannelSnapshot */
        LogChannelSnapshot: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "app" | "jobs" | "desktop" | "legacy-runtime";
            /** Entries */
            entries: components["schemas"]["LogEntry"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** LogEntry */
        LogEntry: {
            /** Entry Id */
            entry_id?: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Channel
             * @enum {string}
             */
            channel: "app" | "jobs" | "desktop" | "legacy-runtime";
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Source */
            source: string;
        };
        /** RuntimeStatus */
        RuntimeStatus: {
            /**
             * Runtime Id
             * @enum {string}
             */
            runtime_id: "spot" | "futures";
            /** Label */
            label: string;
            /**
             * State
             * @enum {string}
             */
            state: "running" | "degraded" | "offline" | "unknown";
            /** Pids */
            pids?: number[];
            /**
             * Pid Count
             * @default 0
             */
            pid_count: number;
            /** Last Heartbeat At */
            last_heartbeat_at?: string | null;
            /** Last Heartbeat Age Seconds */
            last_heartbeat_age_seconds?: number | null;
            /** Last Error */
            last_error?: string | null;
            /** Last Error At */
            last_error_at?: string | null;
            /** Status Reason */
            status_reason: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "fixture" | "compatibility";
        };
        /** RuntimeStatusSnapshot */
        RuntimeStatusSnapshot: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Runtimes */
            runtimes: components["schemas"]["RuntimeStatus"][];
        };
        /** SampleDataImportJobPayload */
        SampleDataImportJobPayload: {
            /**
             * Sleep Ms
             * @default 80
             */
            sleep_ms: number;
        };
        /** SpotBalance */
        SpotBalance: {
            /** Asset */
            asset: string;
            /**
             * Free Qty
             * @default 0
             */
            free_qty: number;
            /**
             * Locked Qty
             * @default 0
             */
            locked_qty: number;
            /**
             * Total Qty
             * @default 0
             */
            total_qty: number;
            /** Source Of Truth */
            source_of_truth?: string | null;
            /** Updated At Utc */
            updated_at_utc?: string | null;
        };
        /** SpotFill */
        SpotFill: {
            /** Account Type */
            account_type: string;
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /** Exec Id */
            exec_id: string;
            /** Order Id */
            order_id?: string | null;
            /** Order Link Id */
            order_link_id?: string | null;
            /**
             * Price
             * @default 0
             */
            price: number;
            /**
             * Qty
             * @default 0
             */
            qty: number;
            /** Fee */
            fee?: number | null;
            /** Fee Currency */
            fee_currency?: string | null;
            /** Is Maker */
            is_maker?: boolean | null;
            /** Exec Time Ms */
            exec_time_ms?: number | null;
            /** Created At Utc */
            created_at_utc?: string | null;
        };
        /** SpotHolding */
        SpotHolding: {
            /** Account Type */
            account_type: string;
            /** Symbol */
            symbol: string;
            /** Base Asset */
            base_asset: string;
            /**
             * Free Qty
             * @default 0
             */
            free_qty: number;
            /**
             * Locked Qty
             * @default 0
             */
            locked_qty: number;
            /**
             * Total Qty
             * @default 0
             */
            total_qty: number;
            /** Avg Entry Price */
            avg_entry_price?: number | null;
            /** Hold Reason */
            hold_reason: string;
            /** Source Of Truth */
            source_of_truth: string;
            /**
             * Recovered From Exchange
             * @default false
             */
            recovered_from_exchange: boolean;
            /** Strategy Owner */
            strategy_owner?: string | null;
            /**
             * Auto Sell Allowed
             * @default false
             */
            auto_sell_allowed: boolean;
            /** Updated At Utc */
            updated_at_utc?: string | null;
        };
        /** SpotOrder */
        SpotOrder: {
            /** Account Type */
            account_type: string;
            /** Symbol */
            symbol: string;
            /** Side */
            side: string;
            /** Order Id */
            order_id?: string | null;
            /** Order Link Id */
            order_link_id?: string | null;
            /** Order Type */
            order_type?: string | null;
            /** Time In Force */
            time_in_force?: string | null;
            /**
             * Price
             * @default 0
             */
            price: number;
            /**
             * Qty
             * @default 0
             */
            qty: number;
            /**
             * Filled Qty
             * @default 0
             */
            filled_qty: number;
            /** Status */
            status: string;
            /** Strategy Owner */
            strategy_owner?: string | null;
            /** Updated At Utc */
            updated_at_utc?: string | null;
        };
        /** SpotReadSnapshot */
        SpotReadSnapshot: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "fixture" | "compatibility";
            summary: components["schemas"]["SpotReadSummary"];
            /** Balances */
            balances?: components["schemas"]["SpotBalance"][];
            /** Holdings */
            holdings?: components["schemas"]["SpotHolding"][];
            /** Active Orders */
            active_orders?: components["schemas"]["SpotOrder"][];
            /** Recent Fills */
            recent_fills?: components["schemas"]["SpotFill"][];
            truncated?: components["schemas"]["SpotReadTruncation"];
        };
        /** SpotReadSummary */
        SpotReadSummary: {
            /** Account Type */
            account_type: string;
            /**
             * Balance Assets Count
             * @default 0
             */
            balance_assets_count: number;
            /**
             * Holdings Count
             * @default 0
             */
            holdings_count: number;
            /**
             * Recovered Holdings Count
             * @default 0
             */
            recovered_holdings_count: number;
            /**
             * Strategy Owned Holdings Count
             * @default 0
             */
            strategy_owned_holdings_count: number;
            /**
             * Open Orders Count
             * @default 0
             */
            open_orders_count: number;
            /**
             * Recent Fills Count
             * @default 0
             */
            recent_fills_count: number;
            /**
             * Pending Intents Count
             * @default 0
             */
            pending_intents_count: number;
        };
        /** SpotReadTruncation */
        SpotReadTruncation: {
            /**
             * Balances
             * @default false
             */
            balances: boolean;
            /**
             * Holdings
             * @default false
             */
            holdings: boolean;
            /**
             * Active Orders
             * @default false
             */
            active_orders: boolean;
            /**
             * Recent Fills
             * @default false
             */
            recent_fills: boolean;
        };
        /** StartJobRequest */
        StartJobRequest: {
            /** Job Type */
            job_type: string;
            /** Payload */
            payload?: components["schemas"]["SampleDataImportJobPayload"] | components["schemas"]["DataBackfillJobPayload"] | components["schemas"]["DataIntegrityJobPayload"] | components["schemas"]["EmptyJobPayload"];
        };
        /** StopJobRequest */
        StopJobRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** TelegramAlertEntry */
        TelegramAlertEntry: {
            /** Ts */
            ts?: string | null;
            /** Alert Type */
            alert_type: string;
            /** Message */
            message: string;
            /**
             * Delivered
             * @default true
             */
            delivered: boolean;
            /**
             * Source
             * @default telegram
             */
            source: string;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** TelegramCommandEntry */
        TelegramCommandEntry: {
            /** Ts */
            ts?: string | null;
            /** Command */
            command: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Chat Id Masked */
            chat_id_masked?: string | null;
            /** Username */
            username?: string | null;
            /** Args */
            args?: string | null;
        };
        /** TelegramConnectivityCheckResult */
        TelegramConnectivityCheckResult: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at?: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "fixture" | "compatibility";
            /**
             * State
             * @enum {string}
             */
            state: "healthy" | "degraded" | "disabled" | "missing_token" | "unknown";
            /** Detail */
            detail?: string | null;
            /** Bot Username */
            bot_username?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /** TelegramErrorEntry */
        TelegramErrorEntry: {
            /** Ts */
            ts?: string | null;
            /** Error */
            error: string;
            /**
             * Source
             * @default telegram
             */
            source: string;
            /**
             * Status
             * @default error
             */
            status: string;
        };
        /** TelegramOpsSnapshot */
        TelegramOpsSnapshot: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Source Mode
             * @enum {string}
             */
            source_mode: "fixture" | "compatibility";
            summary: components["schemas"]["TelegramOpsSummary"];
            /** Recent Commands */
            recent_commands?: components["schemas"]["TelegramCommandEntry"][];
            /** Recent Alerts */
            recent_alerts?: components["schemas"]["TelegramAlertEntry"][];
            /** Recent Errors */
            recent_errors?: components["schemas"]["TelegramErrorEntry"][];
            truncated?: components["schemas"]["TelegramOpsTruncation"];
        };
        /** TelegramOpsSummary */
        TelegramOpsSummary: {
            /**
             * Bot Profile
             * @default default
             */
            bot_profile: string;
            /**
             * Token Profile Name
             * @default TELEGRAM_BOT_TOKEN
             */
            token_profile_name: string;
            /**
             * Token Configured
             * @default false
             */
            token_configured: boolean;
            /**
             * Internal Bot Disabled
             * @default false
             */
            internal_bot_disabled: boolean;
            /**
             * Connectivity State
             * @default unknown
             * @enum {string}
             */
            connectivity_state: "healthy" | "degraded" | "disabled" | "missing_token" | "unknown";
            /** Connectivity Detail */
            connectivity_detail?: string | null;
            /**
             * Allowed Chat Count
             * @default 0
             */
            allowed_chat_count: number;
            /** Allowed Chats Masked */
            allowed_chats_masked?: string[];
            /**
             * Commands Count
             * @default 0
             */
            commands_count: number;
            /**
             * Alerts Count
             * @default 0
             */
            alerts_count: number;
            /**
             * Errors Count
             * @default 0
             */
            errors_count: number;
            /** Last Successful Send */
            last_successful_send?: string | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Startup Status
             * @default unknown
             */
            startup_status: string;
        };
        /** TelegramOpsTruncation */
        TelegramOpsTruncation: {
            /**
             * Recent Commands
             * @default false
             */
            recent_commands: boolean;
            /**
             * Recent Alerts
             * @default false
             */
            recent_alerts: boolean;
            /**
             * Recent Errors
             * @default false
             */
            recent_errors: boolean;
        };
        /** UiCapabilities */
        UiCapabilities: {
            /** Desktop */
            desktop: boolean;
            /** Jobs */
            jobs: boolean;
            /** Routes */
            routes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_bootstrap_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapPayload"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
        };
    };
    start_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_job_jobs__job_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_log_channels_logs_channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogChannel"][];
                };
            };
        };
    };
    get_log_snapshot_logs__channel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogChannelSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_log_channel_logs__channel_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runtime_status_runtime_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatusSnapshot"];
                };
            };
        };
    };
    start_runtime_runtime_control__runtime_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: "spot" | "futures";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_runtime_runtime_control__runtime_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runtime_id: "spot" | "futures";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spot_snapshot_spot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotReadSnapshot"];
                };
            };
        };
    };
    get_futures_snapshot_futures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FuturesReadSnapshot"];
                };
            };
        };
    };
    get_telegram_snapshot_telegram_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramOpsSnapshot"];
                };
            };
        };
    };
    run_telegram_connectivity_check_telegram_connectivity_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramConnectivityCheckResult"];
                };
            };
        };
    };
    shutdown_admin_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
