/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bootstrap */
        get: operations["get_bootstrap_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /** Start Job */
        post: operations["start_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Job */
        post: operations["stop_job_jobs__job_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Log Channels */
        get: operations["list_log_channels_logs_channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log Snapshot */
        get: operations["get_log_snapshot_logs__channel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/{channel_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Log Channel */
        get: operations["stream_log_channel_logs__channel_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown */
        post: operations["shutdown_admin_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppSessionInfo */
        AppSessionInfo: {
            /** Session Id */
            session_id: string;
            /** Transport Base Url */
            transport_base_url: string;
            /** Events Url */
            events_url: string;
        };
        /** BootstrapPayload */
        BootstrapPayload: {
            /** App Name */
            app_name: string;
            /** Version */
            version: string;
            session: components["schemas"]["AppSessionInfo"];
            capabilities: components["schemas"]["UiCapabilities"];
            /** Routes */
            routes: string[];
        };
        /** DataBackfillJobPayload */
        DataBackfillJobPayload: {
            /**
             * Symbol
             * @default BTCUSDT
             * @constant
             */
            symbol: "BTCUSDT";
            /**
             * Category
             * @default spot
             * @constant
             */
            category: "spot";
            /**
             * Intervals
             * @default [
             *       "1m"
             *     ]
             */
            intervals: [
                "1m"
            ];
        };
        /** EmptyJobPayload */
        EmptyJobPayload: Record<string, never>;
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Session Id */
            session_id: string;
        };
        /** JobDetails */
        JobDetails: {
            /** Job Id */
            job_id: string;
            /** Job Type */
            job_type: string;
            state: components["schemas"]["JobState"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Started At */
            started_at?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Exit Code */
            exit_code?: number | null;
            /** Last Error */
            last_error?: string | null;
            /** Log Stream Id */
            log_stream_id?: string | null;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "starting" | "running" | "stopping" | "completed" | "failed" | "cancelled" | "orphaned";
        /** JobSummary */
        JobSummary: {
            /** Job Id */
            job_id: string;
            /** Job Type */
            job_type: string;
            state: components["schemas"]["JobState"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** LogChannel */
        LogChannel: {
            /**
             * Channel Id
             * @enum {string}
             */
            channel_id: "app" | "jobs" | "desktop" | "legacy-runtime";
            /** Label */
            label: string;
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "memory" | "events" | "file" | "compatibility";
            /**
             * Available
             * @default false
             */
            available: boolean;
        };
        /** LogChannelSnapshot */
        LogChannelSnapshot: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "app" | "jobs" | "desktop" | "legacy-runtime";
            /** Entries */
            entries: components["schemas"]["LogEntry"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** LogEntry */
        LogEntry: {
            /** Entry Id */
            entry_id?: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /**
             * Channel
             * @enum {string}
             */
            channel: "app" | "jobs" | "desktop" | "legacy-runtime";
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Source */
            source: string;
        };
        /** SampleDataImportJobPayload */
        SampleDataImportJobPayload: {
            /**
             * Sleep Ms
             * @default 80
             */
            sleep_ms: number;
        };
        /** StartJobRequest */
        StartJobRequest: {
            /** Job Type */
            job_type: string;
            /** Payload */
            payload?: components["schemas"]["SampleDataImportJobPayload"] | components["schemas"]["DataBackfillJobPayload"] | components["schemas"]["EmptyJobPayload"];
        };
        /** StopJobRequest */
        StopJobRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** UiCapabilities */
        UiCapabilities: {
            /** Desktop */
            desktop: boolean;
            /** Jobs */
            jobs: boolean;
            /** Routes */
            routes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_bootstrap_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapPayload"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
        };
    };
    start_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_job_jobs__job_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_log_channels_logs_channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogChannel"][];
                };
            };
        };
    };
    get_log_snapshot_logs__channel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogChannelSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_log_channel_logs__channel_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_admin_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
